title: DaxLib.SVG
description: A comprehensive set of DAX User-Defined Functions (UDF) designed to enable easy creation of SVG visuals for Power BI
remote_theme: just-the-docs/just-the-docs

# Language and locale settings
lang: en
locale: en_US

# SEO settings
author:
  name: EvaluationContext
  url: https://github.com/EvaluationContext
social:
  name: Jake Duddy
  links:
    - https://www.linkedin.com/in/jakeduddy/

# Google Search Console verification
google_site_verification: "SAsOJ1OUHiMcP4hI-eYBkBD6nbsLx6hc2nWjLqdCtd0"

# Giscus Comments Configuration
giscus:
  enabled: true
  repo: "EvaluationContext/daxlib.svg"
  repo_id: "R_kgDOP22Qnw"
  category: "Announcements"
  category_id: "DIC_kwDOP22Qn84CwYnK"
  mapping: "pathname"
  reactions_enabled: 0
  emit_metadata: 0
  input_position: "top"
  theme: "light"
  lang: "en"
  loading: "lazy"

# Remove logo to hide the icon
# logo: "/assets/img/icon.png"
favicon_ico: "/assets/img/favicons/favicon.ico"

# CSS customization
aux_links:
  "GitHub":
    - "https://github.com/EvaluationContext/daxlib.svg"

aux_links_new_tab: true

# Theme settings
color_scheme: light

# Enable or disable the site search
search_enabled: true

# Heading anchor links appear on hover over h1-h6 tags
heading_anchors: true

# External navigation links
nav_external_links:
  - title: DaxLib.org
    url: https://daxlib.org/package/DaxLib.SVG/
    hide_icon: false

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-include-cache

url: "https://evaluationcontext.github.io"
baseurl: "/daxlib.svg"
repository: EvaluationContext/daxlib.svg

permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page"
      comments: true

# PWA settings
pwa:
  enabled: true
  cache:
    enabled: true
    # Files that will not be cached
    deny_paths:
      - /assets/js/data/
      - /sw.min.js

callouts_level: quiet # or loud
callouts:
  info:
    title: Info
    color: blue
  tip:
    title: Tip
    color: green
  warning:
    title: Warning
    color: yellow

kramdown:
  syntax_highlighter: none
  syntax_highlighter_opts: {}

back_to_top: true
back_to_top_text: "Back to top"