site_name: DaxLib.SVG
site_url: https://evaluationcontext.github.io/daxlib.svg/
repo_name: daxlib.svg
repo_url: https://github.com/EvaluationContext/daxlib.svg
site_author: Jake Duddy
site_description: A DAX User-Defined Functions (UDF) library designed to make creating SVG visuals in Power BI easier
theme:
  name: material
  custom_dir: overrides
  language: en
  favicon: assets/images/favicon.ico
  icon:
    repo: fontawesome/brands/github
    logo: material/svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference  
  features:
    # - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    # - content.footnote.tooltips
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    # - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - navigation.footer
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.path
    - toc.follow
    - toc.integrate
  
extra:
  google_site_verification: SAsOJ1OUHiMcP4hI-eYBkBD6nbsLx6hc2nWjLqdCtd0
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jakeduddy/
      name: Jake Duddy
    - icon: fontawesome/brands/github
      link: https://github.com/EvaluationContext
      name: EvaluationContext

plugins:
  - search
  - meta-descriptions

extra_css:
  - assets/css/pill.css
  - assets/css/codeblock.css
  - assets/css/button.css
  - assets/css/colorBlocks.css
  - assets/css/cards.css
  - assets/css/gallery.css
  - assets/css/carousel.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Functions:
      - functions/index.md
      - SVG:
        - svg/index.md
        - SVG: svg/SVG.md
      - Scales:
        - scales/index.md
        - Normalize: scales/Scale.Normalize.md
        - NiceNum: scales/Scale.NiceNum.md
        - NiceRange: scales/Scale.NiceRange.md
      - Data:
        - data/index.md
        - AxisMeasure: data/Data.AxisMeasure.md
        - Range: data/Data.Range.md
      - Axes:
        - axes/index.md
        - MaxTickLabelWidth: axes/Axes.MaxTickLabelWidth.md
        - Layout: axes/Axes.Layout.md
        - Render: axes/Axes.Render.md
        - Point: axes/Axes.Point.md
        - Baseline: axes/Axes.Baseline.md
      - Attributes:
        - attributes/index.md
        - Shapes: attributes/Attr.Shapes.md
        - Stroke: attributes/Attr.Stroke.md
        - Txt: attributes/Attr.Txt.md
      - Transforms:
        - transforms/index.md
        - Transforms: transforms/Transforms.md
      - Elements:
        - elements/index.md
        - Defs: elements/Element.Defs.md
        - UseDef: elements/Element.UseDef.md
        - Group: elements/Element.Group.md
        - Circle: elements/Element.Circle.md
        - Rect: elements/Element.Rect.md
        - Line: elements/Element.Line.md
        - Paths: elements/Element.Paths.md
        - Ellipse: elements/Element.Ellipse.md
        - Polygon: elements/Element.Polygon.md
        - Polyline: elements/Element.Polyline.md
        - Txt: elements/Element.Txt.md
      - Defs:
        - defs/index.md
        - GradientStop: defs/Def.GradientStop.md
        - LinearGradient: defs/Def.LinearGradient.md
        - RadialGradient: defs/Def.RadialGradient.md
        - ClipPath: defs/Def.ClipPath.md
        - Circle: defs/Def.Circle.md
        - Rect: defs/Def.Rect.md
        - Line: defs/Def.Line.md
        - Paths: defs/Def.Paths.md
      - Compounds:
        - compounds/index.md
        - Pill: compounds/Compound.Pill.md
        - Bars: compounds/Compound.Bars.md
        - Line: compounds/Compound.Line.md
        - Area: compounds/Compound.Area.md
        - Jitter: compounds/Compound.Jitter.md
        - ProgressBar: compounds/Compound.ProgressBar.md
        - Boxplot: compounds/Compound.Boxplot.md
        - Violin: compounds/Compound.Violin.md
        - Heatmap: compounds/Compound.Heatmap.md
      - Viz:
        - viz/index.md
        - Bars: viz/Viz.Bars.md
        - Line: viz/Viz.Line.md
        - Area: viz/Viz.Area.md
        - ProgressBar: viz/Viz.ProgressBar.md
        - Pill: viz/Viz.Pill.md
        - Boxplot: viz/Viz.Boxplot.md
        - Jitter: viz/Viz.Jitter.md
        - Heatmap: viz/Viz.Heatmap.md
        - Violin: viz/Viz.Violin.md
      - Colors:
        - colors/index.md
        - Theme: colors/Color.Theme.md
        - PerformanceTheme: colors/Color.PerformanceTheme.md
        - Hex.Interpolate: colors/Color.Hex.Interpolate.md
        - Hex.ToInt: colors/Color.Hex.ToInt.md
        - Int.ToHex: colors/Color.Int.ToHex.md
        - RGB.ToHex: colors/Color.RGB.ToHex.md
  - Change Log: changeLog.md